repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: tests
        name: Running Tests
        language: system
        always_run: true
        pass_filenames: false
        entry: poetry run python -m scripts.tests
      - id: styles
        name: Applying Styles
        language: system
        always_run: true
        pass_filenames: false
        entry: poetry run python -m scripts.styles
      - id: analyze
        name: Code Analysis
        language: system
        always_run: true
        pass_filenames: false
        entry: poetry run python -m scripts.analyze
